### ISSUE TITLE
Post processing fails on Hera after maintenance with out of memory

### ISSUE THREAD

**Issue by lisa-bengtsson** [NOAA-EMC/global-workflow#633]
Machine: Hera

This error started showing up after hera maintenance on 01Feb22.

After the LMOD reversal yesterday, the model ran again, but the post processing fails (with no updates after Hera maintenance) with a out of memory message:

"slurmstepd: error: Detected 1 oom-kill event(s) in StepId=28213791.0. Some of your processes may have been killed by the cgroup out-of-memory handler."

My log file is here:
/scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/logs/2019101900/gfspost001.log

expdir:
/scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/expdir/long_progsigma/

output:
/scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/gfs.20191019/00/atmos/

HOMEgfs path:
/scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/

Thanks,
Lisa

**Comment by rreddy2001** [comment]
Hi Lisa, 

I was curious about the above error, so I took a quick look at it but it seems to have completed normally:
`
hfe03.% grep 'exit code' /scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/logs/2019101900/gfspost001.log.5
Job 27529890 (not serial) finished for user Lisa.Bengtsson in partition hera with exit code 0:0
hfe03.%

hfe03.% grep -i oom /scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/logs/2019101900/gfspost001.log.5
hfe03.%
`
Please let me know if i am looking at the wrong file.

**Comment by lisa-bengtsson** [comment]
Hi! Thanks for taking a look, Kate asked me to provide an example log that was completed before the maintenance, that is the gfspost001.log.5 

After Hera maintenance I get the memory error in gfspost001.log (e.g not the .5)

**Comment by lisa-bengtsson** [comment]
I am trying to rebuild gfs_ncep_post now, and will try rerun the gfspost001 job after building.

**Comment by lisa-bengtsson** [comment]
Ok, that did not work. Same error message after rebuilding:

slurmstepd: error: Detected 1 oom-kill event(s) in StepId=28231120.0. Some of your processes may have been killed by the cgroup out-of-memo\
ry handler

**Comment by lisa-bengtsson** [comment]
@KateFriedman-NOAA do you have a "HERA.env" in a working experiment that I could compare with?

**Comment by KateFriedman-NOAA** [comment]
The HERA.env copy in develop should work, no one has reported any issues with the develop branch on Hera yet this week:

https://github.com/NOAA-EMC/global-workflow/blob/develop/env/HERA.env

@WalterKolczynski-NOAA @JessicaMeixner-NOAA Have you happened to run the develop branch on Hera this week post-maintenance at all? Thanks!

**Comment by wzzheng90** [comment]
@lisa-bengtsson:   I also have an issue on Hera after maintenance (#632) and just now, it got resolved by @aerorahul and others.  Perhaps it would be helpful for your issue. 
Best,

Weizhong

**Comment by lisa-bengtsson** [comment]
@wzzheng90 thank you! What did you update in your .bash_profile and .cshrc environment exactly?

**Comment by wzzheng90** [comment]
@lisa-bengtsson :     Rahul suggested me to do as follows:
   
1)        [ -z "$PS1" ] && return
put this on top of your .bash_profile

2)        if ( ! $?prompt ) exit
put this on. your first line of .cshrc

**Comment by lisa-bengtsson** [comment]
@wzzheng90 thank you for your suggestion, but it does not seem to solve this problem unfortunately

**Comment by wzzheng90** [comment]
@lisa-bengtsson  I also cleaned up my home directory and then copied some necessary files back.

**Comment by lgannoaa** [comment]
@lisa-bengtsson  @wzzheng90 If the issue remains and need assistance from us, please ensure you have KEEPDATA=YES in your config.base to save the DATA directory for debug.
Please save a snapshot of your HOMEgfs, EXPDIR, COM, and this job log file. I see file reading error on reading postxconfig-NT.txt file. 
-rw-r--r-- 1 Lisa.Bengtsson rem 361K Feb  4 19:26 /scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/logs/2019101900/gfspost001.log

**Comment by lisa-bengtsson** [comment]
I restarted the gfspost001 job with KEEPDATA=YES. 

I cannot see the file reading error you alluded to in the log?

**Comment by lisa-bengtsson** [comment]
Can you see the DATA directory you want for debug? I don't know where this would end up.

**Comment by lgannoaa** [comment]
I am debugging now. Thank you for the information.

**Comment by lgannoaa** [comment]
Hi @lisa-bengtsson,
In checking with your run, looks like you are using a very old copy. For example, the post package (cea545) was created in 2020/9/30. You may need to update your package unless there is a requirement for it.

For now, would you please make a backup and replace the following modified files and rerun your post job:
$HOMEgfs/parm/config/config.post 
$HOMEgfs/parm/config/config.resources
$EXPDIR/long_progsigma.xml
using the copy from
  /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/
I would like to take a look at the job log.

**Comment by lisa-bengtsson** [comment]
Hi @lgannoaa , yes it is very old, and I have tried very hard to maintain this version in order to run GFSv16 physics (as it is not possible to run GFSv16 with the develop source code anymore). 

I will do a test as you suggest and let you know. Thank you!

**Comment by lgannoaa** [comment]
Looks like you are try to run GFSv16 physics with export CCPP_SUITE="FV3_GFS_v16beta"
This action happen within forecast jobs. Using a new version of post should not have impact.
Let me prepare step-by-step for your next test - Replace post package. This will allow us to use the latest job resource assignment that has been tested on Hera.

**Comment by lisa-bengtsson** [comment]
Unfortunately copying in your modified suggestions did not change the memory issue I'm running into. You can see the latest log. 

Yes, I could update the post-processing if I can keep my model source code , suite definition and namelist. Thank you.

**Comment by lgannoaa** [comment]
Please try the following:
cd /scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/sorc
mv gfs_post.fd gfs_post.fd-OLD
ln -s /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd
rm -f gfs_ncep_post.fd
ln -s /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd/sorc/ncep_post.fd gfs_ncep_post.fd
cd /scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/scripts
mv exgdas_atmos_nceppost.sh exgdas_atmos_nceppost.sh-OLD
mv exgfs_atmos_nceppost.sh exgfs_atmos_nceppost.sh-OLD
mv exglobal_atmos_pmgr.sh exglobal_atmos_pmgr.sh-OLD
ln -s /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd/scripts/exgdas_atmos_nceppost.sh
ln -s /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd/scripts/exgfs_atmos_nceppost.sh
ln -s /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd/scripts/exglobal_atmos_pmgr.sh
Rerun the post job again

**Comment by lisa-bengtsson** [comment]
It is sitting in queue, should I re-build an executable with these?

**Comment by lisa-bengtsson** [comment]
I get this error: slurmstepd: error: execve(): /scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/exec/gfs_ncep_post: No such file or directory 

Do I need to recompile or change somewhere to not look for gfs_ncep_post?

Thanks

**Comment by lisa-bengtsson** [comment]
In exec:

[Lisa.Bengtsson@hfe03 exec]$ ls -lrt gfs_ncep_post
lrwxrwxrwx 1 Lisa.Bengtsson rem 34 Dec  7  2020 gfs_ncep_post -> ../sorc/gfs_post.fd/exec/ncep_post

If I cd into ../sorc/gfs_post.fd/exec/ncep_post
pwd:
/scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd/exec
[Lisa.Bengtsson@hfe03 exec]$ ls
upp.x

There is only the upp.x

Thanks

**Comment by lisa-bengtsson** [comment]
Hi again,

I linked your executable like this:

ln -s /scratch1/NCEPDEV/stmp2/Lin.Gan/issue-633/gfs_post.fd/exec/upp.x gfs_ncep_post

and started the job again. It fails with the same original error message (out of memory). If no one else is getting these out of memory issues in post-processing after the maintenance, perhaps it is related to my environment?  


============
 FULLMODELNAME: GFS
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=28263224.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=28263224.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: h4c54: task 4: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=28263224.0
slurmstepd: error: *** STEP 28263224.0 ON h4c54 CANCELLED AT 2022-02-05T17:26:45 ***
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
upp.x              00000000014B2B6E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B48A8436630  Unknown               Unknown  Unknown
upp.x              00000000006BEF80  allocate_all_             155  ALLOCATE_ALL.f

**Comment by lisa-bengtsson** [comment]
I also tried updating HERA.env, module_base.hera and load_fv3gfs_modules.sh without any luck..

**Comment by lgannoaa** [comment]
I noticed, you used debug queue in your $EXPDIR/$PSLOT.xml
Please change to the following and rerun your post job.
ENTITY QUEUE      "batch"

**Comment by lisa-bengtsson** [comment]
I get the same problem in the batch queue:

/scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/logs/2019101900/gfspost001.log

**Comment by lisa-bengtsson** [comment]
Do you happen to know if there has been any dialogue with Hera folks if any update they did on February 1st would impact this? I submitted a ticket to their helpdesk as well, but I have not heard back yet.

**Comment by KateFriedman-NOAA** [comment]
Yes, I have been chatting with @RaghuReddy-NOAA offline about the OOM kill in issue #631 and we looked at this one briefly too. Working on the init job OOM kill right now (may be related) and one of the Hera helpdesk folks is looking at whether the SLURM update that happened during last week's maintenance impacted this somehow.

**Comment by KateFriedman-NOAA** [comment]
@lisa-bengtsson Question... @RaghuReddy-NOAA and I were wondering if you modified your HERA.env to set the ulimit to a value instead of unlimited. Saw that while looking through your latest post log.

**Comment by jkhender** [comment]
@lisa-bengtsson @KateFriedman-NOAA   I noticed over the weekend that my chem C384 post jobs have also been failing with an out of memory error since the hera maintenance. I let @RaghuReddy-NOAA know about this as well in email exchanges we had for #631

**Comment by lisa-bengtsson** [comment]
@KateFriedman-NOAA apologies, I tested a lot of different settings in HERA.env over the weekend, all still resulting in memory error. I just now reverted to the HERA.env file that is https://github.com/NOAA-EMC/global-workflow/blob/develop/env/HERA.env and I still see the same message.

**Comment by lisa-bengtsson** [comment]
Also, thanks to the update regarding Hera communication.

**Comment by lgannoaa** [comment]
Your job card needs to be changed. Please replace your:
$EXPDIR/long_progsigma.xml 
with
/scratch1/NCEPDEV/global/Lin.Gan/expdir/issue-633/long_progsigma.xml
And rerun your post job.
You can reference to my completed job log:
/scratch1/NCEPDEV/stmp2/Lin.Gan/ptmp/com/long_progsigma/logs/2019101900/gfspost006.log
If it is done at your satisfy. may I close this ticket?

**Comment by KateFriedman-NOAA** [comment]
@lgannoaa I am testing a fix for both this issue and issue #631. I have gotten the init job to run successfully by specifying memory at submission time. I am testing a gfspost job right now to confirm the same thing helps with that OOM kill. Will send more details after I finish my test on Hera.

**Comment by lisa-bengtsson** [comment]
@KateFriedman-NOAA @jkhender @lgannoaa The suggestion to specify memory at submission time works! I had to go all the way up to 200GB though, without really having a good reference number for memory usage, that sounds pretty high? Do you think it is OK to leave it at 200GB? This experiment is C768.

**Comment by lisa-bengtsson** [comment]
(This is for post processing, did not try initialization yet)

**Comment by rreddy2001** [comment]
@lisa-bengtsson 200 GB definitely seems extremely high!  What was the biggest memory size that you tried that failed? 
Can you point me to your job output file please? Also, do you have the "report-mem" command at the end of the job file to see the amount of memory used?

**Comment by WalterKolczynski-NOAA** [comment]
Specifying too high a number mostly just means you will move through the queue slower and occupy a bigger footprint than needed, but won't impact the actual performance. But that is useful information as we try to determine what value to use in develop.

**Comment by lisa-bengtsson** [comment]
@rreddy2001 This is my log-file:
/scratch2/BMC/rem/Lisa.Bengtsson/ufs_gfsv16_prog_closure/comrot/long_progsigma/logs/2019101900/gfspost001.log

I did try 20GB, 30GB and 100GB, which still did not work, then I went to 200GB, I suppose I could try something closer to 100GB. 

I don't see a "report-mem" command, can you let me know the syntax, I can add it.

**Comment by rreddy2001** [comment]
@lisa-bengtsson Here is the link about getting memory information:
https://rdhpcs-common-docs.rdhpcs.noaa.gov/wiki/index.php/Running_and_Monitoring_Jobs_on_Jet_and_Hera(Theia)_-_SLURM#How_to_Get_Memory_Usage_Information

**Comment by lisa-bengtsson** [comment]
@rreddy2001 

do I add:
 
printenv
report-mem

at the end of long_progsigma.xml or in the post processing task? 

Thanks @WalterKolczynski-NOAA I can try some lower number, hopefully I can see the actual usage

**Comment by WalterKolczynski-NOAA** [comment]
@lisa-bengtsson add it to the bottom of the j-job (the script in the `jobs/` directory) for any jobs you need to profile

**Comment by jkhender** [comment]
@lisa-bengtsson @RaghuReddy-NOAA @WalterKolczynski-NOAA   For my post jobs that were failing with out of memory, I was able to request 40G and mine completed successfully. They are at C384 resolution.

**Comment by lisa-bengtsson** [comment]
@jkhender thanks for the info. My C768 jobs worked for the upper atmosphere, but failed in the surface with 100GB. It works with 200GB. Trying to figure out now what to set.

@WalterKolczynski-NOAA I think I need to revert some of the updates that I did to search for a solution earlier in this thread as the post processing "jobs/" scripts are pointing to /Lin.Gan/ directory and I don't have permission to add anything in those files. I will get back to you with the numbers once I have it all figured out.

**Comment by WalterKolczynski-NOAA** [comment]
@lisa-bengtsson Was this resolved? I haven't heard of any further issues with it.

**Comment by lisa-bengtsson** [comment]
Yes, sorry you can close this issue, it was resolved by specifying the memory needed. Now I have moved on to use the latest workflow.
